language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs-dist // 需部署的文件夹
  on:
    branch: main // 基于main分支进行部署
